USE master
GO
CREATE DATABASE Hotel_HM210444
ON
(NAME=Hotel_HM210444_dat,
FILENAME= 'D:\REPOSITORIOS VS\LAB MDB\Lab 1 MBD\EJERCICIO_COMPLEMENTARIO LAB 1.mdf',
SIZE=5,
MAXSIZE=20,
FILEGROWTH=5)
LOG ON
(NAME=Hotel_HM210444_log,
FILENAME= 'D:\REPOSITORIOS VS\LAB MDB\Lab 1 MBD\EJERCICIO_COMPLEMENTARIO LAB 1.ldf',
SIZE=5,
MAXSIZE=20,
FILEGROWTH=5)
GO